#!/usr/bin/env python3
"""
Convert PyTorch RNNoise model to C-compatible format
Similar to dump_rnn.py but for PyTorch models
"""

import torch
import torch.nn as nn
import numpy as np
import argparse
import sys
from rnn_train_pytorch import RNNoiseModel


def print_vector(f, ft, vector, name):
    """Print weight vector in C format"""
    v = np.reshape(vector, (-1))
    f.write(f'static const rnn_weight {name}[{len(v)}] = {{\n   ')
    
    for i in range(len(v)):
        # Scale and quantize weights (same as original)
        quantized = min(127, int(round(256 * v[i])))
        f.write(f'{quantized}')
        ft.write(f'{quantized}')
        
        if i != len(v) - 1:
            f.write(',')
            ft.write(' ')
            if i % 8 == 7:
                f.write('\n   ')
        else:
            break
    
    f.write('\n};\n\n')
    ft.write('\n')


def extract_gru_weights(gru_layer):
    """Extract GRU weights in the format expected by C implementation"""
    # PyTorch GRU weight layout: [input_weights, hidden_weights]
    # Each has shape [3*hidden_size, input_size] and [3*hidden_size, hidden_size]
    
    state_dict = gru_layer.state_dict()
    
    # Get weights
    weight_ih = state_dict['weight_ih_l0'].detach().cpu().numpy()  # [3*hidden, input]
    weight_hh = state_dict['weight_hh_l0'].detach().cpu().numpy()  # [3*hidden, hidden]
    bias_ih = state_dict['bias_ih_l0'].detach().cpu().numpy()      # [3*hidden]
    bias_hh = state_dict['bias_hh_l0'].detach().cpu().numpy()      # [3*hidden]
    
    # Combine biases
    bias = bias_ih + bias_hh
    
    hidden_size = weight_hh.shape[1]
    input_size = weight_ih.shape[1]
    
    # Reshape weights to match C implementation format
    # C expects: input_weights[input_size * 3 * hidden_size]
    # PyTorch gives: weight_ih[3 * hidden_size, input_size]
    input_weights = weight_ih.T.reshape(-1)  # Transpose and flatten
    
    # C expects: recurrent_weights[hidden_size * 3 * hidden_size]  
    # PyTorch gives: weight_hh[3 * hidden_size, hidden_size]
    recurrent_weights = weight_hh.T.reshape(-1)  # Transpose and flatten
    
    return input_weights, recurrent_weights, bias, input_size, hidden_size


def extract_dense_weights(dense_layer):
    """Extract Dense layer weights"""
    state_dict = dense_layer.state_dict()
    
    weight = state_dict['weight'].detach().cpu().numpy()  # [output, input]
    bias = state_dict['bias'].detach().cpu().numpy()      # [output]
    
    # Transpose weight to match C format [input, output]
    weight = weight.T.reshape(-1)
    
    input_size = weight.shape[0] // bias.shape[0]
    output_size = bias.shape[0]
    
    return weight, bias, input_size, output_size


def get_activation_id(activation_name):
    """Convert activation name to C enum value"""
    activation_map = {
        'tanh': 0,      # ACTIVATION_TANH
        'sigmoid': 1,   # ACTIVATION_SIGMOID  
        'relu': 2       # ACTIVATION_RELU
    }
    return activation_map.get(activation_name.lower(), 0)


def dump_pytorch_model(model_path, output_c_file, output_binary_file, model_name='pytorch'):
    """Dump PyTorch model to C format"""
    
    # Load the model
    checkpoint = torch.load(model_path, map_location='cpu')
    model = RNNoiseModel()
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    
    # Open output files
    with open(output_c_file, 'w') as f, open(output_binary_file, 'w') as ft:
        
        # Write C file header
        f.write('/*This file is automatically generated from a PyTorch model*/\n\n')
        f.write('#ifdef HAVE_CONFIG_H\n#include "config.h"\n#endif\n\n')
        f.write('#include "rnn.h"\n#include "rnn_data.h"\n\n')
        
        # Write binary file header
        ft.write('rnnoise-nu model file version 1\n')
        
        print("Extracting model weights...")
        
        # 1. Input Dense Layer
        print("  Input dense layer...")
        input_weights, input_bias, input_in_size, input_out_size = extract_dense_weights(model.input_dense)
        
        ft.write(f'{input_in_size} {input_out_size} 0\n')  # 0 = TANH activation
        print_vector(f, ft, input_weights, 'input_dense_weights')
        print_vector(f, ft, input_bias, 'input_dense_bias')
        
        f.write('static const DenseLayer input_dense = {\n')
        f.write('   input_dense_bias,\n')
        f.write('   input_dense_weights,\n') 
        f.write(f'   {input_in_size}, {input_out_size}, ACTIVATION_TANH\n')
        f.write('};\n\n')
        
        # 2. VAD GRU Layer
        print("  VAD GRU layer...")
        vad_input_weights, vad_recurrent_weights, vad_bias, vad_in_size, vad_hidden_size = extract_gru_weights(model.vad_gru)
        
        ft.write(f'{vad_in_size} {vad_hidden_size} 0\n')  # 0 = TANH activation
        print_vector(f, ft, vad_input_weights, 'vad_gru_weights')
        print_vector(f, ft, vad_recurrent_weights, 'vad_gru_recurrent_weights')
        print_vector(f, ft, vad_bias, 'vad_gru_bias')
        
        f.write('static const GRULayer vad_gru = {\n')
        f.write('   vad_gru_bias,\n')
        f.write('   vad_gru_weights,\n')
        f.write('   vad_gru_recurrent_weights,\n')
        f.write(f'   {vad_in_size}, {vad_hidden_size}, ACTIVATION_TANH\n')
        f.write('};\n\n')
        
        # 3. Noise GRU Layer  
        print("  Noise GRU layer...")
        noise_input_weights, noise_recurrent_weights, noise_bias, noise_in_size, noise_hidden_size = extract_gru_weights(model.noise_gru)
        
        ft.write(f'{noise_in_size} {noise_hidden_size} 2\n')  # 2 = RELU activation
        print_vector(f, ft, noise_input_weights, 'noise_gru_weights')
        print_vector(f, ft, noise_recurrent_weights, 'noise_gru_recurrent_weights')
        print_vector(f, ft, noise_bias, 'noise_gru_bias')
        
        f.write('static const GRULayer noise_gru = {\n')
        f.write('   noise_gru_bias,\n')
        f.write('   noise_gru_weights,\n')
        f.write('   noise_gru_recurrent_weights,\n')
        f.write(f'   {noise_in_size}, {noise_hidden_size}, ACTIVATION_RELU\n')
        f.write('};\n\n')
        
        # 4. Denoise GRU Layer
        print("  Denoise GRU layer...")
        denoise_input_weights, denoise_recurrent_weights, denoise_bias, denoise_in_size, denoise_hidden_size = extract_gru_weights(model.denoise_gru)
        
        ft.write(f'{denoise_in_size} {denoise_hidden_size} 0\n')  # 0 = TANH activation
        print_vector(f, ft, denoise_input_weights, 'denoise_gru_weights')
        print_vector(f, ft, denoise_recurrent_weights, 'denoise_gru_recurrent_weights')
        print_vector(f, ft, denoise_bias, 'denoise_gru_bias')
        
        f.write('static const GRULayer denoise_gru = {\n')
        f.write('   denoise_gru_bias,\n')
        f.write('   denoise_gru_weights,\n')
        f.write('   denoise_gru_recurrent_weights,\n')
        f.write(f'   {denoise_in_size}, {denoise_hidden_size}, ACTIVATION_TANH\n')
        f.write('};\n\n')
        
        # 5. Denoise Output Layer
        print("  Denoise output layer...")
        denoise_out_weights, denoise_out_bias, denoise_out_in_size, denoise_out_out_size = extract_dense_weights(model.denoise_output)
        
        ft.write(f'{denoise_out_in_size} {denoise_out_out_size} 1\n')  # 1 = SIGMOID activation
        print_vector(f, ft, denoise_out_weights, 'denoise_output_weights')
        print_vector(f, ft, denoise_out_bias, 'denoise_output_bias')
        
        f.write('static const DenseLayer denoise_output = {\n')
        f.write('   denoise_output_bias,\n')
        f.write('   denoise_output_weights,\n')
        f.write(f'   {denoise_out_in_size}, {denoise_out_out_size}, ACTIVATION_SIGMOID\n')
        f.write('};\n\n')
        
        # 6. VAD Output Layer
        print("  VAD output layer...")
        vad_out_weights, vad_out_bias, vad_out_in_size, vad_out_out_size = extract_dense_weights(model.vad_output)
        
        ft.write(f'{vad_out_in_size} {vad_out_out_size} 1\n')  # 1 = SIGMOID activation
        print_vector(f, ft, vad_out_weights, 'vad_output_weights')
        print_vector(f, ft, vad_out_bias, 'vad_output_bias')
        
        f.write('static const DenseLayer vad_output = {\n')
        f.write('   vad_output_bias,\n')
        f.write('   vad_output_weights,\n')
        f.write(f'   {vad_out_in_size}, {vad_out_out_size}, ACTIVATION_SIGMOID\n')
        f.write('};\n\n')
        
        # 7. Main Model Structure
        f.write(f'const struct RNNModel rnnoise_model_{model_name} = {{\n')
        f.write(f'  {input_out_size},\n')
        f.write('  &input_dense,\n')
        f.write(f'  {vad_hidden_size},\n')
        f.write('  &vad_gru,\n')
        f.write(f'  {noise_hidden_size},\n')
        f.write('  &noise_gru,\n')
        f.write(f'  {denoise_hidden_size},\n')
        f.write('  &denoise_gru,\n')
        f.write(f'  {denoise_out_out_size},\n')
        f.write('  &denoise_output,\n')
        f.write(f'  {vad_out_out_size},\n')
        f.write('  &vad_output\n')
        f.write('};\n')
    
    print(f"Model successfully exported to:")
    print(f"  C source: {output_c_file}")
    print(f"  Binary weights: {output_binary_file}")


def main():
    parser = argparse.ArgumentParser(description='Convert PyTorch RNNoise model to C format')
    parser.add_argument('input_model', help='Input PyTorch model file (.pth)')
    parser.add_argument('output_c', help='Output C source file')
    parser.add_argument('output_binary', help='Output binary weights file')
    parser.add_argument('--model-name', default='pytorch', 
                        help='Name for the model in C code (default: pytorch)')
    
    args = parser.parse_args()
    
    try:
        dump_pytorch_model(args.input_model, args.output_c, args.output_binary, args.model_name)
        print("Conversion completed successfully!")
    except Exception as e:
        print(f"Error during conversion: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()